apiVersion: batch/v1
kind: Job
metadata:
  generateName: yt-dlp-720p-
spec:
  template:
    spec:
      containers:
      - name: yt-dlp
        image: yt-dlp:v2
        command: ["yt-dlp",  "-f", "best[height<=720][ext=mp4]", "https://youtu.be/VZk-aMgWxCQ"]
        volumeMounts:
        - name: nfs
          mountPath: /app
      volumes:
      - name: nfs
        nfs:
          server: 192.168.0.40
          path: "/volume1/nas2T/板桥_2025_09_22/Youtube/"
      restartPolicy: Never

